### ISSUE TITLE
Dependency on libnss3-tools

### ISSUE THREAD

**Issue by C-512L** [aruiz/autofirma-flatpak#2]
This is stated as dependency on the official Debian package. I ignore what the program requires it for, but I guess it's better to follow what upstream package does.

**Comment by aruiz** [comment]
I much rather add dependencies based on the actual use case rather than copying the debian package dependencies verbatim. Each dependency is a maintainership burden in flatpak as we have to build and distribute ourselves.

**Comment by C-512L** [comment]
According to [clienteafirma/#381#issuecomment-1999128558](https://github.com/ctt-gob-es/clienteafirma/issues/381#issuecomment-1999128558), it's only used for reading certificate details from a smartcard, which i'm not sure how well it would work on flatpak.
